languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "Code is cheap, let's talk"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "site-logo.png"
  description = "Code is cheap, let's talk"

[params.author]
  name = "ferstar"
  image = "site-logo.png"
  headline = "Code is cheap, let's talk"
  links = [
    { github = "https://github.com/ferstar" },
  ]
