languageCode = "en"
languageName = "English"
weight = 2
title = "Code is cheap, let's talk"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "Jan 2, 2006"
  logo = "site-logo.png"
  description = "Code is cheap, let's talk"

[params.homepage]
  showMoreLink = true

[params.author]
  name = "ferstar"
  image = "site-logo.png"
  headline = "Code is cheap, let's talk"
  links = [
    { github = "https://github.com/ferstar" },
  ]
