[[main]]
  name = "归档"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ferstar"
  weight = 30